#############################################################################
# Makefile for building: qpdfview
# Generated by qmake (2.01a) (Qt 4.8.6) on: vie sep 16 12:28:57 2016
# Project:  application.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile application.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DAPPLICATION_VERSION=\"0.4.16\" -DWITH_SVG -DWITH_SQL -DWITH_DBUS -DPLUGIN_INSTALL_PATH=\"/usr/lib/qpdfview\" -DWITH_PDF -DPOPPLER_VERSION=\"0.47.0\" -DPDF_PLUGIN_NAME=\"libqpdfview_pdf.so\" -DWITH_PS -DLIBSPECTRE_VERSION=\"0.2.7\" -DPS_PLUGIN_NAME=\"libqpdfview_ps.so\" -DWITH_DJVU -DDJVULIBRE_VERSION=\"3.5.25\" -DDJVU_PLUGIN_NAME=\"libqpdfview_djvu.so\" -DWITH_IMAGE -DIMAGE_PLUGIN_NAME=\"libqpdfview_image.so\" -DWITH_CUPS -DCUPS_VERSION=\"1.7.5\" -DWITH_SYNCTEX -DWITH_MAGIC -DWITH_SIGNALS -DDATA_INSTALL_PATH=\"/usr/share/qpdfview\" -DQT_NO_DEBUG -DQT_DBUS_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtDBus -I/usr/include/qt4 -Isynctex -Iicons -I../../../Pruebas/poppler-0.47.0 -I../../../Pruebas/poppler-0.47.0/poppler -Imoc
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
#LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/debian/Pruebas/poppler-0.47.0/poppler/.libs/ -lpoppler -lcups -lz -lmagic -lQtDBus -lQtSvg -lQtSql -lQtGui -lQtCore -lpthread 
LIBS          = $(SUBLIBS) -L/usr/local/lib -lpoppler -L/usr/lib/x86_64-linux-gnu -lcups -lz -lmagic -lQtDBus -lQtSvg -lQtSql -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = objects/

####### Files

SOURCES       = sources/settings.cpp \
		sources/pluginhandler.cpp \
		sources/shortcuthandler.cpp \
		sources/rendertask.cpp \
		sources/tileitem.cpp \
		sources/pageitem.cpp \
		sources/thumbnailitem.cpp \
		sources/presentationview.cpp \
		sources/searchmodel.cpp \
		sources/searchitemdelegate.cpp \
		sources/searchtask.cpp \
		sources/miscellaneous.cpp \
		sources/documentlayout.cpp \
		sources/documentview.cpp \
		sources/printdialog.cpp \
		sources/settingsdialog.cpp \
		sources/fontsdialog.cpp \
		sources/helpdialog.cpp \
		sources/recentlyusedmenu.cpp \
		sources/recentlyclosedmenu.cpp \
		sources/bookmarkmenu.cpp \
		sources/bookmarkdialog.cpp \
		sources/bookmarkmodel.cpp \
		sources/database.cpp \
		sources/mainwindow.cpp \
		sources/main.cpp \
		synctex/synctex_parser.c \
		synctex/synctex_parser_utils.c \
		sources/signalhandler.cpp moc/moc_settings.cpp \
		moc/moc_model.cpp \
		moc/moc_pluginhandler.cpp \
		moc/moc_shortcuthandler.cpp \
		moc/moc_rendertask.cpp \
		moc/moc_tileitem.cpp \
		moc/moc_pageitem.cpp \
		moc/moc_thumbnailitem.cpp \
		moc/moc_presentationview.cpp \
		moc/moc_searchmodel.cpp \
		moc/moc_searchitemdelegate.cpp \
		moc/moc_searchtask.cpp \
		moc/moc_miscellaneous.cpp \
		moc/moc_documentview.cpp \
		moc/moc_printdialog.cpp \
		moc/moc_settingsdialog.cpp \
		moc/moc_fontsdialog.cpp \
		moc/moc_helpdialog.cpp \
		moc/moc_recentlyusedmenu.cpp \
		moc/moc_recentlyclosedmenu.cpp \
		moc/moc_bookmarkmodel.cpp \
		moc/moc_bookmarkmenu.cpp \
		moc/moc_bookmarkdialog.cpp \
		moc/moc_database.cpp \
		moc/moc_mainwindow.cpp \
		moc/moc_signalhandler.cpp \
		qrc_icons.cpp
OBJECTS       = objects/settings.o \
		objects/pluginhandler.o \
		objects/shortcuthandler.o \
		objects/rendertask.o \
		objects/tileitem.o \
		objects/pageitem.o \
		objects/thumbnailitem.o \
		objects/presentationview.o \
		objects/searchmodel.o \
		objects/searchitemdelegate.o \
		objects/searchtask.o \
		objects/miscellaneous.o \
		objects/documentlayout.o \
		objects/documentview.o \
		objects/printdialog.o \
		objects/settingsdialog.o \
		objects/fontsdialog.o \
		objects/helpdialog.o \
		objects/recentlyusedmenu.o \
		objects/recentlyclosedmenu.o \
		objects/bookmarkmenu.o \
		objects/bookmarkdialog.o \
		objects/bookmarkmodel.o \
		objects/database.o \
		objects/mainwindow.o \
		objects/main.o \
		objects/synctex_parser.o \
		objects/synctex_parser_utils.o \
		objects/signalhandler.o \
		objects/moc_settings.o \
		objects/moc_model.o \
		objects/moc_pluginhandler.o \
		objects/moc_shortcuthandler.o \
		objects/moc_rendertask.o \
		objects/moc_tileitem.o \
		objects/moc_pageitem.o \
		objects/moc_thumbnailitem.o \
		objects/moc_presentationview.o \
		objects/moc_searchmodel.o \
		objects/moc_searchitemdelegate.o \
		objects/moc_searchtask.o \
		objects/moc_miscellaneous.o \
		objects/moc_documentview.o \
		objects/moc_printdialog.o \
		objects/moc_settingsdialog.o \
		objects/moc_fontsdialog.o \
		objects/moc_helpdialog.o \
		objects/moc_recentlyusedmenu.o \
		objects/moc_recentlyclosedmenu.o \
		objects/moc_bookmarkmodel.o \
		objects/moc_bookmarkmenu.o \
		objects/moc_bookmarkdialog.o \
		objects/moc_database.o \
		objects/moc_mainwindow.o \
		objects/moc_signalhandler.o \
		objects/qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qpdfview.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		application.pro
QMAKE_TARGET  = qpdfview
DESTDIR       = 
TARGET        = qpdfview

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: application.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		qpdfview.pri \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtDBus.prl \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile application.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
qpdfview.pri:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtDBus.prl:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile application.pro

dist: 
	@$(CHK_DIR_EXISTS) objects/qpdfview1.0.0 || $(MKDIR) objects/qpdfview1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) objects/qpdfview1.0.0/ && $(COPY_FILE) --parents sources/global.h sources/renderparam.h sources/printoptions.h sources/settings.h sources/model.h sources/pluginhandler.h sources/shortcuthandler.h sources/rendertask.h sources/tileitem.h sources/pageitem.h sources/thumbnailitem.h sources/presentationview.h sources/searchmodel.h sources/searchitemdelegate.h sources/searchtask.h sources/miscellaneous.h sources/documentlayout.h sources/documentview.h sources/printdialog.h sources/settingsdialog.h sources/fontsdialog.h sources/helpdialog.h sources/recentlyusedmenu.h sources/recentlyclosedmenu.h sources/bookmarkmodel.h sources/bookmarkmenu.h sources/bookmarkdialog.h sources/database.h sources/mainwindow.h synctex/synctex_parser.h synctex/synctex_parser_utils.h synctex/synctex_parser_local.h sources/signalhandler.h objects/qpdfview1.0.0/ && $(COPY_FILE) --parents icons.qrc objects/qpdfview1.0.0/ && $(COPY_FILE) --parents sources/settings.cpp sources/pluginhandler.cpp sources/shortcuthandler.cpp sources/rendertask.cpp sources/tileitem.cpp sources/pageitem.cpp sources/thumbnailitem.cpp sources/presentationview.cpp sources/searchmodel.cpp sources/searchitemdelegate.cpp sources/searchtask.cpp sources/miscellaneous.cpp sources/documentlayout.cpp sources/documentview.cpp sources/printdialog.cpp sources/settingsdialog.cpp sources/fontsdialog.cpp sources/helpdialog.cpp sources/recentlyusedmenu.cpp sources/recentlyclosedmenu.cpp sources/bookmarkmenu.cpp sources/bookmarkdialog.cpp sources/bookmarkmodel.cpp sources/database.cpp sources/mainwindow.cpp sources/main.cpp synctex/synctex_parser.c synctex/synctex_parser_utils.c sources/signalhandler.cpp objects/qpdfview1.0.0/ && (cd `dirname objects/qpdfview1.0.0` && $(TAR) qpdfview1.0.0.tar qpdfview1.0.0 && $(COMPRESS) qpdfview1.0.0.tar) && $(MOVE) `dirname objects/qpdfview1.0.0`/qpdfview1.0.0.tar.gz . && $(DEL_FILE) -r objects/qpdfview1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_settings.cpp moc/moc_model.cpp moc/moc_pluginhandler.cpp moc/moc_shortcuthandler.cpp moc/moc_rendertask.cpp moc/moc_tileitem.cpp moc/moc_pageitem.cpp moc/moc_thumbnailitem.cpp moc/moc_presentationview.cpp moc/moc_searchmodel.cpp moc/moc_searchitemdelegate.cpp moc/moc_searchtask.cpp moc/moc_miscellaneous.cpp moc/moc_documentview.cpp moc/moc_printdialog.cpp moc/moc_settingsdialog.cpp moc/moc_fontsdialog.cpp moc/moc_helpdialog.cpp moc/moc_recentlyusedmenu.cpp moc/moc_recentlyclosedmenu.cpp moc/moc_bookmarkmodel.cpp moc/moc_bookmarkmenu.cpp moc/moc_bookmarkdialog.cpp moc/moc_database.cpp moc/moc_mainwindow.cpp moc/moc_signalhandler.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_settings.cpp moc/moc_model.cpp moc/moc_pluginhandler.cpp moc/moc_shortcuthandler.cpp moc/moc_rendertask.cpp moc/moc_tileitem.cpp moc/moc_pageitem.cpp moc/moc_thumbnailitem.cpp moc/moc_presentationview.cpp moc/moc_searchmodel.cpp moc/moc_searchitemdelegate.cpp moc/moc_searchtask.cpp moc/moc_miscellaneous.cpp moc/moc_documentview.cpp moc/moc_printdialog.cpp moc/moc_settingsdialog.cpp moc/moc_fontsdialog.cpp moc/moc_helpdialog.cpp moc/moc_recentlyusedmenu.cpp moc/moc_recentlyclosedmenu.cpp moc/moc_bookmarkmodel.cpp moc/moc_bookmarkmenu.cpp moc/moc_bookmarkdialog.cpp moc/moc_database.cpp moc/moc_mainwindow.cpp moc/moc_signalhandler.cpp
moc/moc_settings.cpp: sources/global.h \
		sources/printoptions.h \
		sources/settings.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/settings.h -o moc/moc_settings.cpp

moc/moc_model.cpp: sources/global.h \
		sources/model.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/model.h -o moc/moc_model.cpp

moc/moc_pluginhandler.cpp: sources/pluginhandler.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/pluginhandler.h -o moc/moc_pluginhandler.cpp

moc/moc_shortcuthandler.cpp: sources/shortcuthandler.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/shortcuthandler.h -o moc/moc_shortcuthandler.cpp

moc/moc_rendertask.cpp: sources/renderparam.h \
		sources/global.h \
		sources/rendertask.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/rendertask.h -o moc/moc_rendertask.cpp

moc/moc_tileitem.cpp: sources/global.h \
		sources/tileitem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/tileitem.h -o moc/moc_tileitem.cpp

moc/moc_pageitem.cpp: sources/renderparam.h \
		sources/global.h \
		sources/pageitem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/pageitem.h -o moc/moc_pageitem.cpp

moc/moc_thumbnailitem.cpp: sources/pageitem.h \
		sources/renderparam.h \
		sources/global.h \
		sources/thumbnailitem.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/thumbnailitem.h -o moc/moc_thumbnailitem.cpp

moc/moc_presentationview.cpp: sources/renderparam.h \
		sources/global.h \
		sources/presentationview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/presentationview.h -o moc/moc_presentationview.cpp

moc/moc_searchmodel.cpp: sources/searchmodel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/searchmodel.h -o moc/moc_searchmodel.cpp

moc/moc_searchitemdelegate.cpp: sources/searchitemdelegate.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/searchitemdelegate.h -o moc/moc_searchitemdelegate.cpp

moc/moc_searchtask.cpp: sources/searchtask.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/searchtask.h -o moc/moc_searchtask.cpp

moc/moc_miscellaneous.cpp: sources/miscellaneous.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/miscellaneous.h -o moc/moc_miscellaneous.cpp

moc/moc_documentview.cpp: sources/renderparam.h \
		sources/global.h \
		sources/printoptions.h \
		sources/documentview.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/documentview.h -o moc/moc_documentview.cpp

moc/moc_printdialog.cpp: sources/printdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/printdialog.h -o moc/moc_printdialog.cpp

moc/moc_settingsdialog.cpp: sources/settingsdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/settingsdialog.h -o moc/moc_settingsdialog.cpp

moc/moc_fontsdialog.cpp: sources/fontsdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/fontsdialog.h -o moc/moc_fontsdialog.cpp

moc/moc_helpdialog.cpp: sources/helpdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/helpdialog.h -o moc/moc_helpdialog.cpp

moc/moc_recentlyusedmenu.cpp: sources/recentlyusedmenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/recentlyusedmenu.h -o moc/moc_recentlyusedmenu.cpp

moc/moc_recentlyclosedmenu.cpp: sources/recentlyclosedmenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/recentlyclosedmenu.h -o moc/moc_recentlyclosedmenu.cpp

moc/moc_bookmarkmodel.cpp: sources/bookmarkmodel.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/bookmarkmodel.h -o moc/moc_bookmarkmodel.cpp

moc/moc_bookmarkmenu.cpp: sources/global.h \
		sources/bookmarkmenu.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/bookmarkmenu.h -o moc/moc_bookmarkmenu.cpp

moc/moc_bookmarkdialog.cpp: sources/bookmarkdialog.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/bookmarkdialog.h -o moc/moc_bookmarkdialog.cpp

moc/moc_database.cpp: sources/global.h \
		sources/database.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/database.h -o moc/moc_database.cpp

moc/moc_mainwindow.cpp: sources/renderparam.h \
		sources/global.h \
		sources/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/mainwindow.h -o moc/moc_mainwindow.cpp

moc/moc_signalhandler.cpp: sources/signalhandler.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) sources/signalhandler.h -o moc/moc_signalhandler.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/document-save.svg \
		icons/two-pages-with-cover-page.svg \
		icons/folder.svg \
		icons/view-refresh.svg \
		icons/document-print.svg \
		icons/zoom-out.svg \
		icons/document-save-as.svg \
		icons/two-pages.svg \
		icons/go-next.svg \
		icons/mail-attachment.svg \
		icons/qpdfview.svg \
		icons/fit-to-page-width.svg \
		icons/go-last.svg \
		icons/go-up.svg \
		icons/multiple-pages.svg \
		icons/right-to-left.svg \
		icons/process-stop.svg \
		icons/x-office-presentation.svg \
		icons/edit-find.svg \
		icons/continuous.svg \
		icons/document-open.svg \
		icons/image-loading.svg \
		icons/fit-to-page-size.svg \
		icons/go-down.svg \
		icons/object-rotate-left.svg \
		icons/go-jump.svg \
		icons/image-missing.svg \
		icons/zoom-original.svg \
		icons/media-seek-backward.svg \
		icons/zoom-in.svg \
		icons/tab-new.svg \
		icons/go-previous.svg \
		icons/media-seek-forward.svg \
		icons/object-rotate-right.svg \
		icons/edit-copy.svg \
		icons/go-first.svg \
		icons/view-fullscreen.svg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

objects/settings.o: sources/settings.cpp sources/settings.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/settings.o sources/settings.cpp

objects/pluginhandler.o: sources/pluginhandler.cpp sources/pluginhandler.h \
		sources/model.h \
		sources/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/pluginhandler.o sources/pluginhandler.cpp

objects/shortcuthandler.o: sources/shortcuthandler.cpp sources/shortcuthandler.h \
		sources/documentview.h \
		sources/renderparam.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/shortcuthandler.o sources/shortcuthandler.cpp

objects/rendertask.o: sources/rendertask.cpp sources/rendertask.h \
		sources/renderparam.h \
		sources/global.h \
		sources/model.h \
		sources/settings.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/rendertask.o sources/rendertask.cpp

objects/tileitem.o: sources/tileitem.cpp sources/tileitem.h \
		sources/global.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/rendertask.h \
		sources/renderparam.h \
		sources/pageitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/tileitem.o sources/tileitem.cpp

objects/pageitem.o: sources/pageitem.cpp sources/pageitem.h \
		sources/renderparam.h \
		sources/global.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/model.h \
		sources/rendertask.h \
		sources/tileitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/pageitem.o sources/pageitem.cpp

objects/thumbnailitem.o: sources/thumbnailitem.cpp sources/thumbnailitem.h \
		sources/pageitem.h \
		sources/renderparam.h \
		sources/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/thumbnailitem.o sources/thumbnailitem.cpp

objects/presentationview.o: sources/presentationview.cpp sources/presentationview.h \
		sources/renderparam.h \
		sources/global.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/model.h \
		sources/pageitem.h \
		sources/documentview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/presentationview.o sources/presentationview.cpp

objects/searchmodel.o: sources/searchmodel.cpp sources/searchmodel.h \
		sources/documentview.h \
		sources/renderparam.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/searchmodel.o sources/searchmodel.cpp

objects/searchitemdelegate.o: sources/searchitemdelegate.cpp sources/searchitemdelegate.h \
		sources/searchmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/searchitemdelegate.o sources/searchitemdelegate.cpp

objects/searchtask.o: sources/searchtask.cpp sources/searchtask.h \
		sources/model.h \
		sources/global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/searchtask.o sources/searchtask.cpp

objects/miscellaneous.o: sources/miscellaneous.cpp sources/miscellaneous.h \
		sources/searchmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/miscellaneous.o sources/miscellaneous.cpp

objects/documentlayout.o: sources/documentlayout.cpp sources/documentlayout.h \
		sources/global.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/pageitem.h \
		sources/renderparam.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/documentlayout.o sources/documentlayout.cpp

objects/documentview.o: sources/documentview.cpp sources/documentview.h \
		sources/renderparam.h \
		sources/global.h \
		sources/printoptions.h \
		sources/settings.h \
		sources/model.h \
		sources/pluginhandler.h \
		sources/shortcuthandler.h \
		sources/pageitem.h \
		sources/thumbnailitem.h \
		sources/presentationview.h \
		sources/searchmodel.h \
		sources/searchtask.h \
		sources/miscellaneous.h \
		sources/documentlayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/documentview.o sources/documentview.cpp

objects/printdialog.o: sources/printdialog.cpp sources/printdialog.h \
		sources/settings.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/printdialog.o sources/printdialog.cpp

objects/settingsdialog.o: sources/settingsdialog.cpp sources/settingsdialog.h \
		sources/settings.h \
		sources/global.h \
		sources/printoptions.h \
		sources/model.h \
		sources/pluginhandler.h \
		sources/shortcuthandler.h \
		sources/documentview.h \
		sources/renderparam.h \
		sources/miscellaneous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/settingsdialog.o sources/settingsdialog.cpp

objects/fontsdialog.o: sources/fontsdialog.cpp sources/fontsdialog.h \
		sources/settings.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/fontsdialog.o sources/fontsdialog.cpp

objects/helpdialog.o: sources/helpdialog.cpp sources/helpdialog.h \
		sources/settings.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/helpdialog.o sources/helpdialog.cpp

objects/recentlyusedmenu.o: sources/recentlyusedmenu.cpp sources/recentlyusedmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/recentlyusedmenu.o sources/recentlyusedmenu.cpp

objects/recentlyclosedmenu.o: sources/recentlyclosedmenu.cpp sources/recentlyclosedmenu.h \
		sources/documentview.h \
		sources/renderparam.h \
		sources/global.h \
		sources/printoptions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/recentlyclosedmenu.o sources/recentlyclosedmenu.cpp

objects/bookmarkmenu.o: sources/bookmarkmenu.cpp sources/bookmarkmenu.h \
		sources/global.h \
		sources/miscellaneous.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/bookmarkmenu.o sources/bookmarkmenu.cpp

objects/bookmarkdialog.o: sources/bookmarkdialog.cpp sources/bookmarkdialog.h \
		sources/global.h \
		sources/bookmarkmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/bookmarkdialog.o sources/bookmarkdialog.cpp

objects/bookmarkmodel.o: sources/bookmarkmodel.cpp sources/bookmarkmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/bookmarkmodel.o sources/bookmarkmodel.cpp

objects/database.o: sources/database.cpp sources/database.h \
		sources/global.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/documentview.h \
		sources/renderparam.h \
		sources/bookmarkmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/database.o sources/database.cpp

objects/mainwindow.o: sources/mainwindow.cpp sources/mainwindow.h \
		sources/renderparam.h \
		sources/global.h \
		sources/model.h \
		sources/settings.h \
		sources/printoptions.h \
		sources/shortcuthandler.h \
		sources/thumbnailitem.h \
		sources/pageitem.h \
		sources/searchmodel.h \
		sources/searchitemdelegate.h \
		sources/documentview.h \
		sources/miscellaneous.h \
		sources/printdialog.h \
		sources/settingsdialog.h \
		sources/fontsdialog.h \
		sources/helpdialog.h \
		sources/recentlyusedmenu.h \
		sources/recentlyclosedmenu.h \
		sources/bookmarkmodel.h \
		sources/bookmarkmenu.h \
		sources/bookmarkdialog.h \
		sources/database.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/mainwindow.o sources/mainwindow.cpp

objects/main.o: sources/main.cpp sources/renderparam.h \
		sources/global.h \
		sources/documentview.h \
		sources/printoptions.h \
		sources/database.h \
		sources/mainwindow.h \
		sources/signalhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/main.o sources/main.cpp

objects/synctex_parser.o: synctex/synctex_parser.c synctex/synctex_parser_local.h \
		synctex/synctex_parser.h \
		synctex/synctex_parser_utils.h \
		/usr/include/zlib.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/synctex_parser.o synctex/synctex_parser.c

objects/synctex_parser_utils.o: synctex/synctex_parser_utils.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o objects/synctex_parser_utils.o synctex/synctex_parser_utils.c

objects/signalhandler.o: sources/signalhandler.cpp sources/signalhandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/signalhandler.o sources/signalhandler.cpp

objects/moc_settings.o: moc/moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_settings.o moc/moc_settings.cpp

objects/moc_model.o: moc/moc_model.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_model.o moc/moc_model.cpp

objects/moc_pluginhandler.o: moc/moc_pluginhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_pluginhandler.o moc/moc_pluginhandler.cpp

objects/moc_shortcuthandler.o: moc/moc_shortcuthandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_shortcuthandler.o moc/moc_shortcuthandler.cpp

objects/moc_rendertask.o: moc/moc_rendertask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_rendertask.o moc/moc_rendertask.cpp

objects/moc_tileitem.o: moc/moc_tileitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_tileitem.o moc/moc_tileitem.cpp

objects/moc_pageitem.o: moc/moc_pageitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_pageitem.o moc/moc_pageitem.cpp

objects/moc_thumbnailitem.o: moc/moc_thumbnailitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_thumbnailitem.o moc/moc_thumbnailitem.cpp

objects/moc_presentationview.o: moc/moc_presentationview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_presentationview.o moc/moc_presentationview.cpp

objects/moc_searchmodel.o: moc/moc_searchmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_searchmodel.o moc/moc_searchmodel.cpp

objects/moc_searchitemdelegate.o: moc/moc_searchitemdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_searchitemdelegate.o moc/moc_searchitemdelegate.cpp

objects/moc_searchtask.o: moc/moc_searchtask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_searchtask.o moc/moc_searchtask.cpp

objects/moc_miscellaneous.o: moc/moc_miscellaneous.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_miscellaneous.o moc/moc_miscellaneous.cpp

objects/moc_documentview.o: moc/moc_documentview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_documentview.o moc/moc_documentview.cpp

objects/moc_printdialog.o: moc/moc_printdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_printdialog.o moc/moc_printdialog.cpp

objects/moc_settingsdialog.o: moc/moc_settingsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_settingsdialog.o moc/moc_settingsdialog.cpp

objects/moc_fontsdialog.o: moc/moc_fontsdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_fontsdialog.o moc/moc_fontsdialog.cpp

objects/moc_helpdialog.o: moc/moc_helpdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_helpdialog.o moc/moc_helpdialog.cpp

objects/moc_recentlyusedmenu.o: moc/moc_recentlyusedmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_recentlyusedmenu.o moc/moc_recentlyusedmenu.cpp

objects/moc_recentlyclosedmenu.o: moc/moc_recentlyclosedmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_recentlyclosedmenu.o moc/moc_recentlyclosedmenu.cpp

objects/moc_bookmarkmodel.o: moc/moc_bookmarkmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_bookmarkmodel.o moc/moc_bookmarkmodel.cpp

objects/moc_bookmarkmenu.o: moc/moc_bookmarkmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_bookmarkmenu.o moc/moc_bookmarkmenu.cpp

objects/moc_bookmarkdialog.o: moc/moc_bookmarkdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_bookmarkdialog.o moc/moc_bookmarkdialog.cpp

objects/moc_database.o: moc/moc_database.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_database.o moc/moc_database.cpp

objects/moc_mainwindow.o: moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_mainwindow.o moc/moc_mainwindow.cpp

objects/moc_signalhandler.o: moc/moc_signalhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/moc_signalhandler.o moc/moc_signalhandler.cpp

objects/qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/qrc_icons.o qrc_icons.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_data: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/qpdfview/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/qpdfview/ 
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ast.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_az.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_be.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_bg.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_bs.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ca.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_cs.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_da.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_de.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_el.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_en_GB.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_eo.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_es.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_eu.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_fi.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_fr.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_gl.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_he.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_hr.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_hu.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_id.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_it.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_kk.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ky.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_lt.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ms.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_my.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_pl.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_pt.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_pt_BR.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ro.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ru.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_sk.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_sv.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_th.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_tr.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_ug.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_uk.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_vi.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/translations/qpdfview_zh_CN.qm $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_az.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_bg.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_cs.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_de.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_en_GB.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_es.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_fa.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_fi.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_fr.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_gl.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_it.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_ko.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_ms.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_pl.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_pt.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_pt_BR.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_ru.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_sk.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_sv.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_uk.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_vi.html $(INSTALL_ROOT)/usr/share/qpdfview/
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/help/help_zh_CN.html $(INSTALL_ROOT)/usr/share/qpdfview/


uninstall_data:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ast.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_az.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_be.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_bg.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_bs.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ca.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_cs.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_da.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_de.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_el.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_en_GB.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_eo.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_es.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_eu.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_fi.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_fr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_gl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_he.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_hr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_hu.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_id.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_it.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_kk.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ky.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_lt.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ms.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_my.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_pl.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_pt.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_pt_BR.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ro.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ru.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_sk.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_sv.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_th.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_tr.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_ug.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_uk.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_vi.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/qpdfview_zh_CN.qm 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_az.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_bg.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_cs.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_de.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_en_GB.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_es.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_fa.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_fi.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_fr.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_gl.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_it.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_ko.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_ms.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_pl.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_pt.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_pt_BR.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_ru.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_sk.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_sv.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_uk.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_vi.html 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qpdfview/help_zh_CN.html
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qpdfview/ 


install_manual: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/man/man1/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/man/man1/ 
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/miscellaneous/qpdfview.1 $(INSTALL_ROOT)/usr/share/man/man1/


uninstall_manual:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/man/man1/qpdfview.1
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/man/man1/ 


install_icon: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/ 
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/icons/qpdfview.svg $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/


uninstall_icon:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/qpdfview.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/ 


install_launcher: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/applications/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/applications/ 
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/miscellaneous/qpdfview.desktop $(INSTALL_ROOT)/usr/share/applications/


uninstall_launcher:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qpdfview.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_appdata: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/share/appdata/ || $(MKDIR) $(INSTALL_ROOT)/usr/share/appdata/ 
	-$(INSTALL_FILE) /home/debian/Descargas/qpdfview-0.4.16_comparation/qpdfview-0.4.16_pedro/miscellaneous/qpdfview.appdata.xml $(INSTALL_ROOT)/usr/share/appdata/


uninstall_appdata:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/appdata/qpdfview.appdata.xml
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/appdata/ 


install:  install_target install_data install_manual install_icon install_launcher install_appdata  FORCE

uninstall: uninstall_target uninstall_data uninstall_manual uninstall_icon uninstall_launcher uninstall_appdata   FORCE

FORCE:

